//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHAT
    {
        public int ID_ACHAT { get; set; }
        public string QUANTITE_ACHAT { get; set; }
        public decimal TOTAL_ACHAT { get; set; }
        public Nullable<int> ID_FOURNISSEUR { get; set; }
        public Nullable<int> ID_PRODUIT { get; set; }
        public Nullable<int> ID_LIVRAISON { get; set; }
        public Nullable<int> ID_CAISSE { get; set; }
    
        public virtual CAISSE CAISSE { get; set; }
        public virtual FOURNISSEUR FOURNISSEUR { get; set; }
        public virtual LIVRAISON LIVRAISON { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
