//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDANT
    {
        public int ID_ANTECEDANT { get; set; }
        public string TYPE_ANTECEDANT { get; set; }
        public string DESCRIP_ANTECEDANT { get; set; }
        public string TRAITEMNT_HABITUEL_OCCASIONEL { get; set; }
    }
}
