//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAISSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAISSE()
        {
            this.ACHATs = new HashSet<ACHAT>();
            this.DEPENSE_CLINIQUE = new HashSet<DEPENSE_CLINIQUE>();
        }
    
        public int ID_CAISSE { get; set; }
        public System.DateTime DATE_CAISSE { get; set; }
        public decimal SOMME_PAYE { get; set; }
        public Nullable<int> ID_PAIEMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHAT> ACHATs { get; set; }
        public virtual PAIEMENT PAIEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPENSE_CLINIQUE> DEPENSE_CLINIQUE { get; set; }
    }
}
