//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMBRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHAMBRE()
        {
            this.HOSPITALISATIONs = new HashSet<HOSPITALISATION>();
        }
    
        public int ID_CHAMBRE { get; set; }
        public string NBR_LIT { get; set; }
        public Nullable<int> ID_SERVICE { get; set; }
    
        public virtual SERVICEE SERVICEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSPITALISATION> HOSPITALISATIONs { get; set; }
    }
}
