//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cliniqueEntities : DbContext
    {
        public cliniqueEntities()
            : base("name=cliniqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACHAT> ACHATs { get; set; }
        public virtual DbSet<ANTECEDANT> ANTECEDANTs { get; set; }
        public virtual DbSet<AUTORISATION> AUTORISATIONs { get; set; }
        public virtual DbSet<CAISSE> CAISSEs { get; set; }
        public virtual DbSet<CAPTURATION_IMAGE> CAPTURATION_IMAGE { get; set; }
        public virtual DbSet<CHAMBRE> CHAMBREs { get; set; }
        public virtual DbSet<CLINIQUE> CLINIQUEs { get; set; }
        public virtual DbSet<CONSOMATION> CONSOMATIONs { get; set; }
        public virtual DbSet<CONSULTATION> CONSULTATIONs { get; set; }
        public virtual DbSet<DEPARTEMENT> DEPARTEMENTs { get; set; }
        public virtual DbSet<DEPENSE_CLINIQUE> DEPENSE_CLINIQUE { get; set; }
        public virtual DbSet<EMPLOYE> EMPLOYEs { get; set; }
        public virtual DbSet<EQUIPEMENT> EQUIPEMENTs { get; set; }
        public virtual DbSet<EXAMan> EXAMEN { get; set; }
        public virtual DbSet<FACTURE> FACTUREs { get; set; }
        public virtual DbSet<FOURNISSEUR> FOURNISSEURs { get; set; }
        public virtual DbSet<LIVRAISON> LIVRAISONs { get; set; }
        public virtual DbSet<MALADIE> MALADIEs { get; set; }
        public virtual DbSet<MEDECIN> MEDECINs { get; set; }
        public virtual DbSet<MEDICAMENT> MEDICAMENTs { get; set; }
        public virtual DbSet<PAIEMENT> PAIEMENTs { get; set; }
        public virtual DbSet<PATIENT> PATIENTs { get; set; }
        public virtual DbSet<PRODUIT> PRODUITs { get; set; }
        public virtual DbSet<RDV> RDVs { get; set; }
        public virtual DbSet<RESULTAT_PATIENT> RESULTAT_PATIENT { get; set; }
        public virtual DbSet<SERVICEE> SERVICEEs { get; set; }
        public virtual DbSet<STOCK> STOCKs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UTILISATEUR> UTILISATEURs { get; set; }
        public virtual DbSet<HOSPITALISATION> HOSPITALISATIONs { get; set; }
        public virtual DbSet<PRESCRIRE> PRESCRIREs { get; set; }
    }
}
