//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSOMATION
    {
        public int ID_CONSOMATION { get; set; }
        public string PRODUIT_CONSOME { get; set; }
        public string QUANTITE_CONSOME { get; set; }
        public System.DateTime DAT_CONSOMATION { get; set; }
        public Nullable<int> ID_STOCK { get; set; }
    
        public virtual STOCK STOCK { get; set; }
    }
}
