//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPENSE_CLINIQUE
    {
        public int ID_DEPENSE { get; set; }
        public decimal MONTANT_RETIRE { get; set; }
        public string JUSTIFICATION { get; set; }
        public System.DateTime DATE_DEPENSE { get; set; }
        public Nullable<int> ID_CAISSE { get; set; }
        public Nullable<int> ID_MEDECIN { get; set; }
    
        public virtual CAISSE CAISSE { get; set; }
        public virtual MEDECIN MEDECIN { get; set; }
    }
}
