//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYE()
        {
            this.FACTUREs = new HashSet<FACTURE>();
            this.RDVs = new HashSet<RDV>();
            this.UTILISATEURs = new HashSet<UTILISATEUR>();
        }
    
        public int ID_EMPLOYE { get; set; }
        public string NOM_EMPLOYE { get; set; }
        public string PRENOM_EMPLOYE { get; set; }
        public System.DateTime DATEN_E { get; set; }
        public string SEXE_EMPLOYE { get; set; }
        public string TEL1_EMPLOYE { get; set; }
        public string TEL2_EMPLOYE { get; set; }
        public string EMAIL_EMPLOYE { get; set; }
        public string SITUATION_FAMILIALE_E { get; set; }
        public string GROUPAGE_E { get; set; }
        public string NIVEAU_ETUDE { get; set; }
        public string ADRESSE_EMPLOYE { get; set; }
        public decimal SALAIRE_E { get; set; }
        public string NUM_CCP_E { get; set; }
        public string NUM_ASSUR_E { get; set; }
        public string STATUT { get; set; }
        public string ROTATION { get; set; }
        public Nullable<int> ID_SERVICE { get; set; }
    
        public virtual SERVICEE SERVICEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURE> FACTUREs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDV> RDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILISATEUR> UTILISATEURs { get; set; }
    }
}
