//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMan()
        {
            this.CONSULTATIONs = new HashSet<CONSULTATION>();
            this.RESULTAT_PATIENT = new HashSet<RESULTAT_PATIENT>();
        }
    
        public int ID_EXAMEN { get; set; }
        public string NOM_EXAM { get; set; }
        public string OBSERVATION_EXAM { get; set; }
        public decimal PRIX_EXAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTATION> CONSULTATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTAT_PATIENT> RESULTAT_PATIENT { get; set; }
    }
}
