//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURE
    {
        public int ID_FACTURE { get; set; }
        public System.DateTime DATE_OPERATION { get; set; }
        public string INTITULE { get; set; }
        public Nullable<decimal> VERSEMENT { get; set; }
        public Nullable<decimal> RESTE { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<decimal> ANCIEN_CREDIT { get; set; }
        public string VALIDE_FACTURE { get; set; }
        public Nullable<int> ID_FOURNISSEUR { get; set; }
        public Nullable<int> ID_EMPLOYE { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual FOURNISSEUR FOURNISSEUR { get; set; }
    }
}
