//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOURNISSEUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOURNISSEUR()
        {
            this.ACHATs = new HashSet<ACHAT>();
            this.FACTUREs = new HashSet<FACTURE>();
            this.LIVRAISONs = new HashSet<LIVRAISON>();
        }
    
        public int ID_FOURNISSEUR { get; set; }
        public string NOM_FOURNISSEUR { get; set; }
        public string TEL1_FOURNISSEUR { get; set; }
        public string TEL2_FOURNISSEUR { get; set; }
        public string ADRESSE_FOURNISSEUR { get; set; }
        public string EMAIL_FOURNISSEUR { get; set; }
        public string PROFFESSION_FOURNISSEUR { get; set; }
        public Nullable<decimal> CREDIT_FOURNISSEUR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHAT> ACHATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURE> FACTUREs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIVRAISON> LIVRAISONs { get; set; }
    }
}
