//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSPITALISATION
    {
        public Nullable<int> ID_PATIENT { get; set; }
        public Nullable<int> ID_SERVICE { get; set; }
        public Nullable<int> ID_CHAMBRE { get; set; }
        public string lit { get; set; }
        public System.DateTime date_host { get; set; }
        public Nullable<int> ID_AUTORISATION { get; set; }
    
        public virtual AUTORISATION AUTORISATION { get; set; }
        public virtual CHAMBRE CHAMBRE { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        public virtual SERVICEE SERVICEE { get; set; }
    }
}
