//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDECIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDECIN()
        {
            this.CONSULTATIONs = new HashSet<CONSULTATION>();
            this.DEPENSE_CLINIQUE = new HashSet<DEPENSE_CLINIQUE>();
            this.RDVs = new HashSet<RDV>();
            this.UTILISATEURs = new HashSet<UTILISATEUR>();
        }
    
        public int ID_MEDECIN { get; set; }
        public string NOM_MEDECIN { get; set; }
        public string PRENOM_MEDECIN { get; set; }
        public System.DateTime DATEN_M { get; set; }
        public string SEXE_MEDECIN { get; set; }
        public string TEL1_MEDECIN { get; set; }
        public string TEL2_MEDECIN { get; set; }
        public string EMAIL_MEDECIN { get; set; }
        public string SITUATION_FAMILIALE_M { get; set; }
        public string GROUPAGE_M { get; set; }
        public string SPECIALITE { get; set; }
        public string ADRESSE_MEDECIN { get; set; }
        public decimal SALAIRE_M { get; set; }
        public string NUM_CCP_M { get; set; }
        public string NUM_ASSUR_M { get; set; }
        public Nullable<int> ID_SERVICE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTATION> CONSULTATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPENSE_CLINIQUE> DEPENSE_CLINIQUE { get; set; }
        public virtual SERVICEE SERVICEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDV> RDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UTILISATEUR> UTILISATEURs { get; set; }
    }
}
