//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAIEMENT()
        {
            this.CAISSEs = new HashSet<CAISSE>();
            this.CONSULTATIONs = new HashSet<CONSULTATION>();
        }
    
        public int ID_PAIEMENT { get; set; }
        public string MODE_PAIEMENT { get; set; }
        public System.DateTime DATE_PAIEMENT { get; set; }
        public Nullable<decimal> VERSEMENT_PAIEMENT { get; set; }
        public Nullable<decimal> RESTE_PAIEMENT { get; set; }
        public Nullable<decimal> TOTAL_PAIEMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAISSE> CAISSEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTATION> CONSULTATIONs { get; set; }
    }
}
