//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT()
        {
            this.CONSULTATIONs = new HashSet<CONSULTATION>();
            this.HOSPITALISATIONs = new HashSet<HOSPITALISATION>();
            this.RDVs = new HashSet<RDV>();
        }
    
        public int ID_PATIENT { get; set; }
        public string NOM_PATIENT { get; set; }
        public string PRENOM_PATIENT { get; set; }
        public System.DateTime DATEN_P { get; set; }
        public string SEXE_PATIENT { get; set; }
        public string TEL1_PATIENT { get; set; }
        public string TEL2_PATIENT { get; set; }
        public string EMAIL_PATIENT { get; set; }
        public string SITUATION_FAMILIALE { get; set; }
        public string GROUPAGE { get; set; }
        public string PROFFESION { get; set; }
        public string ADRESSE_PATIENT { get; set; }
        public string NUM_ASSUR_P { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTATION> CONSULTATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOSPITALISATION> HOSPITALISATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDV> RDVs { get; set; }
    }
}
