//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESCRIRE
    {
        public Nullable<int> ID_CONSULTATION { get; set; }
        public Nullable<int> ID_MEDICAMENT { get; set; }
        public string POSOLOGIE { get; set; }
        public string DUREE_TRAITEMENT { get; set; }
    
        public virtual CONSULTATION CONSULTATION { get; set; }
        public virtual MEDICAMENT MEDICAMENT { get; set; }
    }
}
