//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTAT_PATIENT
    {
        public int ID_RESULTAT_PATIENT { get; set; }
        public System.DateTime DATE_RESULTAT_PATIENT { get; set; }
        public string COMPTE_RENDU_RESULTATP { get; set; }
        public string OBSERVATION_RESULTAT_PATIENT { get; set; }
        public Nullable<int> ID_CONSULTATION { get; set; }
        public Nullable<int> ID_EXAMEN { get; set; }
        public Nullable<int> ID_CAPTURATION_IMAGE { get; set; }
        public Nullable<int> ID_CLINIQUE { get; set; }
    
        public virtual CAPTURATION_IMAGE CAPTURATION_IMAGE { get; set; }
        public virtual CLINIQUE CLINIQUE { get; set; }
        public virtual CONSULTATION CONSULTATION { get; set; }
        public virtual EXAMan EXAMan { get; set; }
    }
}
