//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK()
        {
            this.CONSOMATIONs = new HashSet<CONSOMATION>();
        }
    
        public int ID_STOCK { get; set; }
        public System.DateTime DATE_STOCK { get; set; }
        public string QUANTITE_ENTRE { get; set; }
        public string QUANTITE_SORTIE { get; set; }
        public string QUANTITE_REEL { get; set; }
        public Nullable<int> ID_PRODUIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSOMATION> CONSOMATIONs { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
