//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Cabinet_medicale
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        public int ID_UTILISATEUR { get; set; }
        public string NOM_UTILISATEUR { get; set; }
        public string MTPS { get; set; }
        public Nullable<int> ID_MEDECIN { get; set; }
        public Nullable<int> ID_EMPLOYE { get; set; }
    
        public virtual EMPLOYE EMPLOYE { get; set; }
        public virtual MEDECIN MEDECIN { get; set; }
    }
}
